version: '3.7'

volumes:
  gems-generic_ror_6:

services:
  generic_ror_6:
    build: .
    image: 'src_generic_ror_6'
    environment:
      DATABASE_URL: 'postgresql://postgres@dbhost/'
      TZ:           'America/Sao_Paulo'
    links:
      - db-generic_ror_6:dbhost
    depends_on:
      - db-generic_ror_6
    ports:
      - '3000:3000'
      - '3035:3035'
    volumes:
      - gems-generic_ror_6:/usr/local/bundle
      - .:/usr/src/app:cached
    command: bash -c 'rm -f tmp/pids/server.pid && foreman start -f Procfile.dev'

  db-generic_ror_6:
    image: postgres:9.4.9
    environment:
      POSTGRES_DB:   generic_ror_6_development
      POSTGRES_USER: user
    ports:
      - '5432:5432'
